### ISSUE TITLE
Autostart with KMS grab

### ISSUE THREAD

**Issue by Anvil5465** [flathub/dev.lizardbyte.app.Sunshine#183]
I have tried making a system service for sunshine with KMS grab enabled, but I have been running into a lot of problems. Initially, the service simply wouldn't start at boot, but I was able to overcome this with a sudo crontab job (`@reboot sleep 30 && systemctl start sunshine.service`). However, I have reached a dead end that I can't seem to fix. For some reason, if sunshine is launched using my system service, it fails to create an audio device and stream the computer's audio. My system service file is below. I am using Ubuntu 24.10. Any help would be greatly appreciated.

```
[Unit]
Description=Sunshine self-hosted game stream host for Moonlight.
StartLimitIntervalSec=500
StartLimitBurst=5

[Service]
ExecStart=/bin/bash -c "PULSE_SERVER=unix:$(pactl info | awk '/Server String/{print$3}') flatpak run dev.lizardbyte.app.Sunshine"
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=graphical-session.target
```

**Comment by ReenigneArcher** [comment]
Here's some references for you:

- https://github.com/LizardByte/Sunshine/issues/2839
- https://github.com/LizardByte/Sunshine/issues/3261
- https://github.com/LizardByte/Sunshine/issues/2840

We definitely need to improve the instructions around flatpak, but I'll close this since it will be handled upstream and then propagate here to flathub.

**Comment by Anvil5465** [comment]
Thanks so much this is super helpful
